version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myproject
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: side_quests_db
      POSTGRES_USER: side_quests_user
      POSTGRES_PASSWORD: V7RdwnwM0tBwPJ7jXhoK

