# Use an official Python runtime as a parent image
FROM python:3.12

ENV PYTHONUNBUFFERED 1
#### DONT USE IN PROD
ENV PYTHONDONTWRITEBYTECODE 1

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.dev.txt requirements.common.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.dev.txt -r requirements.common.txt

# Copy the current directory contents into the container at /app
COPY . .

# Expose port 8000 to the outside world
EXPOSE 8000

# Define the command to run when the container starts
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# Need to set to non-root user in prod (needs to match actual user on host)
# USER app