services:
  
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile-prod
    image: scoreboard_caddy_prod
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data_prod:/data
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: scoreboard_django_prod
    container_name: django
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && daphne config.asgi:application -b 0.0.0.0 -p 8000"
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis


  celery:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: scoreboard_celery_prod
    container_name: celery
    restart: unless-stopped
    user: app
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis
      - django

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: scoreboard_celerybeat_prod
    container_name: celerybeat
    restart: unless-stopped
    user: app
    command: ["celery", "-A", "config", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis
      - django

  flower:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: scoreboard_flower_prod
    container_name: flower
    restart: unless-stopped
    ports:
      - 5555:5555
    user: app
    command: ["celery", "-A", "config", "--broker=redis://redis:6379/0", "flower"]
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis
      - django


  redis:
    image: redis:7.4.2
    container_name: redis
    restart: unless-stopped

  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod


volumes:
  postgres_data_prod:
  caddy_data_prod: