# Generated by Django 5.1 on 2025-04-03 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='terminating_score',
            new_name='roborace_score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.badge'),
        ),
        migrations.AddField(
            model_name='score',
            name='badge_boolean',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='roborace_boolean',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='badge_score',
            field=models.FloatField(default=0),
        ),
    ]
