# Generated by Django 5.1 on 2025-03-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(unique=True)),
                ('initials', models.CharField(unique=True)),
                ('deep_easy_hs', models.FloatField(blank=True, null=True)),
                ('deep_easy_win_count', models.IntegerField(blank=True, null=True)),
                ('deep_easy_fail_count', models.IntegerField(blank=True, null=True)),
                ('deep_norm_hs', models.FloatField(blank=True, null=True)),
                ('deep_norm_win_count', models.IntegerField(blank=True, null=True)),
                ('deep_norm_fail_count', models.IntegerField(blank=True, null=True)),
                ('deep_hard_hs', models.FloatField(blank=True, null=True)),
                ('deep_hard_win_count', models.IntegerField(blank=True, null=True)),
                ('deep_hard_fail_count', models.IntegerField(blank=True, null=True)),
                ('deep_official_hs', models.FloatField(blank=True, null=True)),
                ('deep_official_win_count', models.IntegerField(blank=True, null=True)),
                ('deep_official_fail_count', models.IntegerField(blank=True, null=True)),
                ('added', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
