# Generated by Django 5.1 on 2025-04-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_rename_terminating_score_score_roborace_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='badge_boolean',
        ),
        migrations.RemoveField(
            model_name='score',
            name='roborace_boolean',
        ),
    ]
