# Generated by Django 5.1 on 2025-03-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='initials',
            field=models.CharField(blank=True, null=True),
        ),
    ]
