# Generated by Django 5.1 on 2025-04-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_remove_score_badge_boolean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='badge_score',
        ),
    ]
