# Generated by Django 5.1 on 2025-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_remove_score_badge_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='badge_score',
            field=models.FloatField(default=0),
        ),
    ]
