# Generated by Django 5.1 on 2025-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_score_badge_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='roborace_score',
            new_name='roborace_easy_score',
        ),
        migrations.AddField(
            model_name='score',
            name='roborace_hard_score',
            field=models.FloatField(default=0),
        ),
    ]
